[server.pv.error]
no_permissions = "&cLo siento, pero no tienes permiso para ejecutar este comando. Por favor, ponte en contacto con un administrador si crees que esto es un error."
player_only_command = "&cSolo jugadores pueden ejecutar este comando"
player_not_found = "Jugador no encontrado"
mod_missing_kick_message = """
Lo sentimos, necesitas instalar el mod Plasmo Voice para jugar en este servidor.
Descárgalo aquí: https://modrinth.com/plugin/plasmo-voice"""
version_not_supported = "Lo sentimos, tu versión de Plasmo Voice no es compatible con este servidor. %s"
version_not_supported_click = "Descargar versión compatible"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "Sin especificar"
temporarily_muted = "Has sido silenciado %1$s. Motivo: %2$s"
permanently_muted = "Has sido silenciado de forma permanente. Motivo: %s"
unmuted = "Ya no estás silenciado"

  [server.pv.mutes.durations]
  seconds = "durante %s seg"
  minutes = "durante %s min"
  hours = "durante %s h"
  days = "durante %s d"
  weeks = "durante %s sem"

[server.pv.command.mute]
usage = "Uso correcto: /vmute <player> [duration] [reason]"
already_muted = "%s ya se encuentra silenciado."
temporarily_muted = "%1$s ha sido silenciado %2$s. Motivo: %3$s"
permanently_muted = "%1$s ha sido silenciado permanentemente. Motivo: %2$s"

[server.pv.command.unmute]
usage = "Uso correcto: /vunmute <player>"
not_muted = "%s no se encuentra silenciado."
unmuted = "%s ya no está silenciado."

[server.pv.command.mute_list]
header = "Jugadores silenciados:"
entry = "%1$s, expira: %2$s. Motivo: %3$s"
entry_muted_by = "%1$s fue silenciado por %2$s, expira: %3$s. Motivo: %4$s"
empty = "No hay jugadores silenciados"
expire_at = "%1$s en %2$s"
never_expires = "Nunca"
expiration_date = "dd/MM/yyyy"
expiration_time = "HH:mm:ss"

[server.pv.command.list]
message = "Clientes (%1$s/%2$s): %3$s"
empty = "No hay jugadores con Plasmo Voice instalado."

[server.pv.command.reconnect]
message = "Paquete de reconexión enviado."

[server.pv.command.reload]
message = "Configuración Recargada."

[client.pv.activation]
proximity = "Proximidad"
