[server.pv.error]
no_permissions = "&cPrzepraszamy, lecz nie posiadasz permisji, aby wykonać to polecenie. Skontaktuj się z administratorami serwera, jeżeli uważasz, że jest to błąd."
player_only_command = "Tylko gracze mogą wykonywać to polecenie"
player_not_found = "Gracz nie odnaleziony"
mod_missing_kick_message = """
Przepraszamy, musisz zainstalować modyfikację Plasmo Voice, aby grać na tym serwerze.
Pobierz tutaj: https://modrinth.com/plugin/plasmo-voice"""
version_not_supported = "Przepraszamy, Twoja wersja Plasmo Voice nie jest wspierana na tym serwerze. %s"
version_not_supported_click = "Pobierz wspieraną wersję"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "nie określono"
temporarily_muted = "Zostałeś wyciszony %1$s. Powód: %2$s"
permanently_muted = "Zostałeś permanentnie wyciszony. Powód %s"
unmuted = "Zostałeś odciszony"

  [server.pv.mutes.durations]
  seconds = "na %s s"
  minutes = "na %s min"
  hours = "na %s godz"
  days = "na %s d"
  weeks = "na %s tyg"

[server.pv.command.mute]
usage = "Użycie: /vmute <gracz> [długość] [powód]"
already_muted = "%s jest już wyciszony"
temporarily_muted = "Wyciszono %1$s %2$s. Powód: %3$s"
permanently_muted = "%1$s jest permanentnie wyciszony. Powód: %2$s"

[server.pv.command.unmute]
usage = "Użycie: /vunmute <gracz>"
not_muted = "%s nie jest wyciszony"
unmuted = "Odciszono %s"

[server.pv.command.mute_list]
header = "Wyciszeni gracze:"
entry = "%1$s, wygasa: %2$s. Powód: %3$s"
entry_muted_by = "%1$s wyciszony przez %2$s, wygasa: %3$s. Powód: %4$s"
empty = "Żadni gracze nie są wyciszeni"
expire_at = "%1$s o %2$s"
never_expires = "nigdy"
expiration_date = "dd.MM.yyyy"
expiration_time = "HH:mm:ss"

[server.pv.command.list]
message = "Klienci (%1$s/%2$s): %3$s"
empty = "brak graczy z zainstalowanym Plasmo Voice"

[server.pv.command.reconnect]
message = "Pakiety ponownego połączenia wysłane"

[server.pv.command.reload]
message = "Przeładowano konfigurację"

[client.pv.activation]
proximity = "Zbliżeniowy"
