[server.pv.error]
no_permissions = "&cDesculpe, mas você não tem permissão para executar este comando. Por favor contate os administradores do servidor se você acredita que isto é um erro."
player_only_command = "&cApenas jogadores podem usar esse comando"
player_not_found = "Jogador não encontrado"
mod_missing_kick_message = """
Desculpe, você precisa instalar o Plasmo Voice mod para jogar neste servidor.
Baixe aqui: https://modrinth.com/plugin/plasmo-voice"""
version_not_supported = "Desculpe, sua versão do Plasmo Voice não é suportada neste servidor. %s"
version_not_supported_click = "Baixar versão suportada"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "não especificado"
temporarily_muted = "Você foi silenciado %1$s. Motivo: %2$s"
permanently_muted = "Você foi silenciado permanentemente. Motivo: %s"
unmuted = "Você foi desmutado"

  [server.pv.mutes.durations]
  seconds = "por %s seg"
  minutes = "por %s min"
  hours = "por %s h"
  days = "por %s d"
  weeks = "para %s sem"

[server.pv.command.mute]
usage = "Uso: /vmute <player> [duration] [reason]"
already_muted = "%s já está silenciado"
temporarily_muted = "Silenciado %1$s %2$s. Motivo: %3$s"
permanently_muted = "%1$s está silenciado permanentemente. Motivo: %2$s"

[server.pv.command.unmute]
usage = "Uso: /vmute <player>"
not_muted = "%s não está silenciado"
unmuted = "Desmutou %s"

[server.pv.command.mute_list]
header = "Jogadores silenciados:"
entry = "%1$s, expira em: %2$s. Motivo: %3$s"
entry_muted_by = "%1$s silenciado por %2$s, expira em %3$s. Motivo: %4$s"
empty = "Nenhum jogador está silenciado"
expire_at = "%1$s em %2$s"
never_expires = "nunca"
expiration_date = "dd/MM/yyyy"
expiration_time = "HH:mm:ss"

[server.pv.command.list]
message = "Clientes (%1$s/%2$s): %3$s"
empty = "nenhum jogador com Plasmo Voice instalado"

[server.pv.command.reconnect]
message = "Pacote de reconexão enviado"

[server.pv.command.reload]
message = "Configuração recarregada"

[client.pv.activation]
proximity = "Proximidade"
