# Should activate sculks while sneaking
sneak_activation = true
# Allowed double values: [-60.0;0.0]
# Default value: -30.0
activation_threshold = -30.0
# Allowed values: https://minecraft.fandom.com/wiki/Sculk_Sensor#Redstone_emission
# Default value: minecraft:eat
game_event = "minecraft:eat"

# Here you can enable or disable activations. For example:
# groups = true # activates sculks while speaking in groups
# whisper = true # activates sculks while using whisper
# 
# Default value will be used if distance in activation is 0
[activations]
default = false
